Decimal point
metamath/set.mm pull request #2400
Opened 2021-12-26 16:40 UTC by tirix

2021-12-26 16:57 UTC, benjub approved these changes

2021-12-26 16:57 UTC, benjub commented on set.mm
> +  $( Decimal multiplicatin galore! (Contributed by Thierry Arnoux,
multiplication

2021-12-26 17:18 UTC, benjub commented
Using ax-1cn instead of ax1cn should do the trick.

2021-12-26 18:42 UTC, avekens approved these changes

2021-12-26 18:42 UTC, avekens commented on set.mm
> +       Arnoux, 25-Dec-2021.) $)
I think we should use 10 instead of ` ; 1 0 `  within a comment.

2021-12-26 18:45 UTC, avekens requested changes
CI checks  failed: "hgt750lem2" should not use ax1cn, but ax-1cn instead..

2021-12-27 07:42 UTC, avekens approved these changes

2021-12-27 07:42 UTC, avekens commented on set.mm
> +       Arnoux, 25-Dec-2021.) $)
Ok now

2021-12-27 11:26 UTC, benjub approved these changes

2021-12-28 03:00 UTC, merged

2021-12-28 20:19 UTC, david-a-wheeler commented
@tirix - thanks! I'm hoping that eventually decimal points will move into the main body, since we now have multiple users. I hear other people sometimes use decimal points :-).