mathbox cleanup: 4 lemmas renamed according to convention
metamath/set.mm pull request #2479
Opened 2022-02-07 20:35 UTC by glacode

A minimal cleanup:

~ xlimmnflemim1 and ~ xlimmnflemim2 were actually lemmas for xlimmnfv

~ xlimpnflemim1 and ~ xlimpnflemim2 were actually lemmas for xlimpnfv

Thus, they've been renamed to

~ xlimmnfvlem1 , ~ xlimmnfvlem2 , ~ xlimpnfvlem1 , ~ xlimpnfvlem2

according to our convention.

2022-02-07 21:27 UTC, avekens requested changes
If these theorems are actually lemmas only, this should be reflected in their comments. This means that the comments should start with "Lemma for ~ xlimmnfv : ...". This is used to show or suppress lemmas in theorem lists (see option /SHOW_LEMMAS for WRITE THEOREM_LIST).

2022-02-07 22:44 UTC, benjub commented
I agree with @avekens. And they should be labeled and commented as "lemmas" only if they have no interest in themselves (that is, if nothing would be lost if they were simply "inlined" in the proofs of the theorems for which they are lemmas).

2022-02-08 06:23 UTC, jkingdon approved these changes

2022-02-09 12:01 UTC, benjub commented
Merging. Hopefully @glacode can implement @avekens's remarks in a near-future PR.

2022-02-09 12:01 UTC, merged