prove in that order: vpwex > pwexg > pwex
metamath/set.mm pull request #2754
Opened 2022-08-09 22:51 UTC by benjub

The following three successive theorems are currently proved in that order:
* http://us2.metamath.org/mpeuni/pwex.html
* http://us2.metamath.org/mpeuni/vpwex.html from pwex
* http://us2.metamath.org/mpeuni/pwexg.html from vpwex

But vpwex is actlually the penultimate proof step of pwex. Therefore, Prove vpwex first, then pwexg from it (proof unchanged), and finally pwex from pwexg.  This shortens the total number of proof steps (both essential and total).

As for the comments: I did check the referenced book, and their statement is actually vpwex, which is the main theorem, so I gathered information there, keeping the credit to the original contributors.

2022-08-09 23:17 UTC, benjub commented
Second commit: for later theorems, there is no need to go out of our way to avoid dependency on some logical axioms, but in the present case, we are at the very early stages of set theory (still basic theorems to help use the language of classes), and the avoided axioms are the auxiliary schemes, so avoiding them is still worth the work at this stage.

2022-08-09 23:39 UTC, benjub commented
Third and last commit (ignoring the rewrap's): vnex was proved from vprc but was actually a proof step in it, so prove vprc from vnex instead, shortening combined proof length (both essential and total steps).

2022-08-10 00:43 UTC, wlammen approved these changes

2022-08-10 00:46 UTC, wlammen commented
I have no access to the TakeutiZaring, so I cannot check whether its removal from pwexg is justified.  The technical changes are ok, though.  That's what the approval covers.

2022-08-10 06:01 UTC, avekens requested changes

2022-08-10 06:01 UTC, avekens commented on set.mm
> -  $( The universal class does not exist.  (Contributed by NM, 4-Jul-2005.) $)
Although this is the original comment: this is a little bit confusing. Of course does the universal class "exist" (as a class). We should write "The universal class is not a set", shouldn't we?

2022-08-10 06:01 UTC, avekens commented on set.mm
> -  $( The universal class does not exist.  (Contributed by NM, 4-Jul-2005.) $)
Sorry, my comment is at the wrong place... It belongs to ~vnex.

2022-08-10 09:42 UTC, benjub commented on set.mm
> -  $( The universal class does not exist.  (Contributed by NM, 4-Jul-2005.) $)
I changed it to "does not exist as a set" (since the statement reads "E. x x = ...").

2022-08-10 09:43 UTC, benjub commented on set.mm
> -  $( The universal class does not exist.  (Contributed by NM, 4-Jul-2005.) $)
@avekens : can you approve that new commit ?

2022-08-10 09:56 UTC, avekens approved these changes

2022-08-10 10:12 UTC, merged