reduce axioms in number elementhood proofs
metamath/set.mm pull request #2881
Opened 2022-10-08 18:30 UTC by icecream17

rename 2cnOLD -> 2cnALT, as noted in https://github.com/metamath/set.mm/pull/2872
and also reorder rpssre

2022-10-08 23:29 UTC, benjub commented
To me, mergeable after that typo is fixed.

2022-10-09 01:12 UTC, wlammen requested changes
I think you should add rpreOLD and rpssreOLD.  Otherwise well done. Reduction in axiom usage confirmed for all but rpre and rpssre.  The latter are an obvious shortening.

2022-10-09 12:02 UTC, benjub commented
> I think you should add rpreOLD and rpssreOLD. Otherwise well done. Reduction in axiom usage confirmed for all but rpre and rpssre. The latter are an obvious shortening.

To me, the swap rpre <-> rpssre is straightforward enough that there is no need to keep OLD versions, but if @wlammen thinks there is, then let it be so.

2022-10-09 12:30 UTC, benjub commented on changes-set.txt
> + 8-Oct-22 2cnOLD    2cnALT
Not needed since we have 2cn with identical statement anyway.

2022-10-09 14:45 UTC, wlammen commented
> if @wlammen thinks there is, then let it be so.

Why only do I feel being criticized here?

I don't know why my personal opinion plays any role here.  I almost never look at OLD versions, and I am often annoyed because they litter pages like 'Nearby theorems'.  That's why I am often keen to remove outdated ones early.

But it is an established habit to create these, for whatever reason, and there might be people around regarding them as important.  
So I let general ideas prevail.

2022-10-09 16:45 UTC, avekens commented
I also think rpreOLD and rpssreOLD should be added. Afterwards, i will accept this PR.

2022-10-09 17:22 UTC, benjub commented
> Why only do I feel being criticized here?

That was really not my intent. Quite the opposite: it's because I know you have experience with this that I say "if @wlammen  thinks this, then let it be so". If that came from someone totally new to set.mm, I would be more likely to go over their opinion.

2022-10-11 22:13 UTC, icecream17 commented
this took a while, sorry


I made a new pr with all the commented updates:
https://github.com/metamath/set.mm/pull/2888

2022-10-11 22:13 UTC, closed without merging