misc
metamath/set.mm pull request #3137
Opened 2023-04-25 18:29 UTC by icecream17

several small misc changes

explain df-unit
minimize 3prm
fix typos

mathbox:
sbtv + sn-vexvw
remulcan2d
closure for non-subgroup-members
shorten ex-decpmul; update comment

2023-04-25 20:42 UTC, jkingdon commented
The tests did not because of #3134 as seen at https://github.com/metamath/set.mm/actions/runs/4800935603

2023-04-26 16:48 UTC, wlammen approved these changes
I wonder whether you want your name added to 3prm.
The CI checks should be triggered again (by submitting a small and unimportant change like an empty line)

2023-04-26 17:40 UTC, wlammen requested changes
Trigger a CI check

2023-04-26 22:44 UTC, wlammen approved these changes

2023-04-27 00:06 UTC, merged