Improvement of ~2sqreu*
metamath/set.mm pull request #3277
Opened 2023-07-03 16:27 UTC by avekens

Follow up of PR #3260

After proving ~reu3op, it was easy to prove that the representations ` E! p e. ( A X. B ) ph ` with ` p = <. a , b >. ` and ` ( E! x e. A E. y e. B ph /\ E! y e. B E. x e. A ph ) ` for "there are unique ` a ` and ` b ` so that .." are equivalent, see ~opreu2reurex. By this theorem, I could provide variants of the ~2sqreu* theorems with quantification over orderes pairs easily.

For one theorem I provide two variants:
* ~2sqreuopnnltb ``( P e. Prime -> ( ( P mod 4 ) = 1
                          <-> E! p e. ( NN X. NN ) ( ( 1st ` p ) < ( 2nd ` p ) /\ ( ( ( 1st ` p ) ^ 2 ) + ( ( 2nd ` p ) ^ 2 ) ) = P ) ) )`` 
* ~2sqreuopb: `( P e. Prime -> ( ( P mod 4 ) = 1
                          <-> E! p e. ( NN X. NN ) E. a E. b ( p = <. a , b >.  /\ ( a < b /\ ( ( a ^ 2 ) + ( b ^ 2 ) ) = P ) ) ) )`

Although the second variant is a little bit shorter, it has two additional quantifiers, which I do not like much. Therefore, I have no preferences which of these variants to use (in additional cases - for the current case, both variants should remain available for demonstration purposes).

Details:

Main set.mm:
* theorems ~reu3op, ~opreuopreu added
* theorem ~opreu2reurex1  replaced by ~opreu2reurex
* theorems ~addsq2nreurex and ~addsqn2reurex2 added
* comment of ~addsqnreup revised
* variants of ~2sqreu* using quantification over ordered pairs added

AV's mathbox:
* examples for restricted universal quantification in which the restricting class depends on the bound variable (~ralndv1, ~ralndv2)

2023-07-03 17:55 UTC, wlammen requested changes

2023-07-03 17:55 UTC, wlammen commented on set.mm
> +    $( There is a a unique ordered pair fulfilling a wff iff its components
"... a a ..." -> "... a ..."

2023-07-03 17:55 UTC, wlammen commented on set.mm
> +
Nice to have such examples at hand for reasoning about defining restricted quantification as ' A. x ( x e. A -> ph ) '

2023-07-03 20:16 UTC, avekens commented on set.mm
> +    $( There is a a unique ordered pair fulfilling a wff iff its components
fixed

2023-07-03 23:19 UTC, wlammen approved these changes
A non-blocking remark: Consider using variables ph, ps, ch, th ... in this order.

2023-07-05 05:05 UTC, merged

2023-07-05 05:07 UTC, avekens commented
Merged, so that we can go ahead with #3280.