Equation 1 and 2 of lcm inequality lemma
metamath/set.mm pull request #3964
Opened 2024-04-29 17:06 UTC by metakunt

See https://www3.nd.edu/~andyp/notes/AKS.pdf
For the next part I will need itgpowd, so I've moved it to main. 

Also I've changed cniccibl to its choice free version. I am wondering if we need countable choice to define integrals.

2024-04-29 20:14 UTC, wlammen requested changes

2024-04-29 20:14 UTC, wlammen commented on set.mm
> +  $( The closed unit interval is a subset of the set of the complext numbers.
typo: complext

2024-04-29 20:14 UTC, wlammen commented on set.mm
> +       the least common multiple of 1 to n is a integer.  (Contributed by
typo: is an integer

2024-04-29 20:43 UTC, avekens commented
> For the next part I will need itgpowd, so I've moved it to main.

Theorems should not be moved to main unless they are actually used. We cannot be sure if they will be used in the (near) future, so such a moving cannot be approved.

2024-04-29 21:11 UTC, metakunt commented
Alright, I guess I'll move this to draft until I can prove lcmineqlem3

2024-04-30 01:58 UTC, wlammen approved these changes, later dismissed

2024-04-30 13:15 UTC, metakunt commented
I finished proving lcmineqlem3 @avekens As expected it uses itgpowd

2024-04-30 17:07 UTC, avekens approved these changes

2024-04-30 17:26 UTC, tirix approved these changes

2024-04-30 18:43 UTC, merged

2024-05-01 17:30 UTC, tirix commented
FYI, the proof with "math display" is out here: [http://metamath.tirix.org:3030/mpests/lcmineqlem3](http://metamath.tirix.org:3030/mpests/lcmineqlem3)