remove axioms in copsex2g; revise opelopabsbALT
metamath/set.mm pull request #4180
Opened 2024-09-01 16:47 UTC by icecream17

see comment of commit

This changes brabsb2 from Rodolfo Medina's mathbox

2024-09-01 17:14 UTC, benjub requested changes

2024-09-01 17:14 UTC, benjub commented on set.mm
> +       (Revised by SN, 1-Sep-2024.) $)
```suggestion
       28-May-1995.)  Use a similar proof to ~ copsex4g to reduce axiom
       usage.  (Revised by SN, 1-Sep-2024.) $)
```

2024-09-01 17:27 UTC, benjub commented
Does this complete what you wrote in https://github.com/metamath/set.mm/pull/4176#issue-2497834645, e.g., for brabga ?

If you don't have time or motivation to do elrab2gw, maybe you can simply add a comment to elrab2g, e.g.,
> It is possible to prove a weaker version "elrab2gw" not requiring ~ ax-10 , ~ ax-11 , ~ ax-12 , as is ~ elab2gw to ~ elab2g , and use that weaker version instead of ~ elrab2g in most of its applications.

2024-09-01 17:40 UTC, tirix approved these changes

2024-09-02 22:31 UTC, benjub commented
> Does this complete what you wrote in [#4176 (comment)](https://github.com/metamath/set.mm/pull/4176#issue-2497834645), e.g., for brabga ?
> 
> If you don't have time or motivation to do elrab2gw, maybe you can simply add a comment to elrab2g, e.g.,
> 
> > It is possible to prove a weaker version "elrab2gw" not requiring ~ ax-10 , ~ ax-11 , ~ ax-12 , as is ~ elab2gw to ~ elab2g , and use that weaker version instead of ~ elrab2g in most of its applications.

@icecream17 I don't know how to interpret your :+1: :
* what about brabga ?
* will you do the same work with elrab2gw ? or will you add a kind of comment to it as I suggested ?

2024-09-02 23:19 UTC, icecream17 commented
+ ~ brabga indeed does not depend on ax-10 -- ax-12 anymore. (This is what I meant by 👍; my mind was kind of in a trance so I didn't notice the ambiguity)
+ I ended up adding elrab2w (elab2g ~~ elrab2, without g), and used it in one theorem: https://github.com/metamath/set.mm/pull/4185 (relevant commit is the last one). It doesn't seem like there is as much use for elrab2w though... perhaps just having a comment might be a better idea?

![image](https://github.com/user-attachments/assets/1da2dd2a-5cc0-413d-b287-6870ed8fe2af)

Since I have [many TODOs](https://gist.github.com/icecream17/c85a1288ccebd09e21c7609943a9a8d6), I'm trying to do about one or two at a time, hence the separate pr. (Usually, any particular TODO leads to more things, so this is a good unit of measurement).

2024-09-03 00:02 UTC, benjub approved these changes

2024-09-03 00:05 UTC, merged