Reduce ax-8 usage
metamath/set.mm pull request #4184
Opened 2024-09-02 08:50 UTC by GinoGiotto

A few more axiom usage revisions, specifically:

* Edit [rzal](https://us.metamath.org/mpeuni/rzal.html) -> avoid df-clel, ax-8
* Edit [rexn0](https://us.metamath.org/mpeuni/rexn0.html) -> avoid df-clel, ax-8
* Edit [ralidm](https://us.metamath.org/mpeuni/ralidm.html) -> avoid df-clel, df-cleq, ax-8, ax-9, ax-ext
* Edit [ral0](https://us.metamath.org/mpeuni/ral0.html) -> avoid df-clel, ax-8
* Edit [ralf0](https://us.metamath.org/mpeuni/ralf0.html) -> avoid df-clel, ax-8

Note: I used `(/) = { x | F. }` in the proofs of [rzal](https://us.metamath.org/mpeuni/rzal.html) and [ralf0](https://us.metamath.org/mpeuni/ralf0.html).

Axiom usage here: https://github.com/metamath/set.mm/commit/4f41272666476da49a4ae56275ce1fa8b49d4e9c

2024-09-02 10:54 UTC, tirix approved these changes

2024-09-03 00:25 UTC, benjub commented
> Note: I used `(/) = { x | F. }` in the proofs of [rzal](https://us.metamath.org/mpeuni/rzal.html) and [ralf0](https://us.metamath.org/mpeuni/ralf0.html).

Feel free to move https://us.metamath.org/mpeuni/bj-df-nul.html to Main, as, e.g., dfnul4.

2024-09-03 06:37 UTC, GinoGiotto commented
> Feel free to move [us.metamath.org/mpeuni/bj-df-nul.html](https://us.metamath.org/mpeuni/bj-df-nul.html) to Main, as, e.g., dfnul4.

Done. I changed its proof to avoid ax-8.

2024-09-03 18:54 UTC, benjub requested changes

2024-09-03 18:54 UTC, benjub commented on set.mm
> +     30-Nov-2019.) $)
Probably credit is due to you, here. Something like `Avoid ~ ax-8 , ~ df-clel .  (Revised by GG, ...`

2024-09-03 18:54 UTC, benjub commented on set.mm
> +    rzalOLD $p |- ( A = (/) -> A. x e. A ph ) $=
I would say "ALT" since much shorter ?

2024-09-03 21:42 UTC, icecream17 approved these changes
ab0 can be shortened by expanding df-nul (or dfnul4) and using abbi (no cost to axioms)

I can't tell right now, but there's a chance this could be useful to shorten one of the theorems in this pr

2024-09-03 22:00 UTC, benjub commented
> ab0 can be shortened by expanding df-nul (or dfnul4) and using abbi (no cost to axioms)
> 
> I can't tell right now, but there's a chance this could be useful to shorten one of the theorems in this pr

Can you do that in a separate PR ?

2024-09-04 08:55 UTC, GinoGiotto commented
> ab0 can be shortened by expanding df-nul (or dfnul4) and using abbi (no cost to axioms)

In general, I have a preference for ~abbii over ~abbi, because ~abbi requires ax-10, ax-11, ax-12 and it seems none of them can be removed (I've attempted it in the past without success). This makes it a theorem with rather limited applications, but it's fine in particular cases like ~ab0 since it uses those axioms already.

2024-09-05 21:36 UTC, benjub approved these changes

2024-09-05 21:38 UTC, merged